import {
  Shield,
  Database,
  Clock,
  UserCheck,
  CheckSquare,
  Globe,
  Brain,
  AlertTriangle,
  Lock,
  Eye,
  FileText,
  ChevronDown,
} from "lucide-react";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { Navbar } from "@/components/safeguard/Navbar";
import { Footer } from "@/components/safeguard/Footer";

const privacyPrinciples = [
  {
    icon: Database,
    title: "No Permanent Video Storage",
    description:
      "Videos uploaded to SafeGuard MU are never written to permanent storage. They are transferred directly to the Google Gemini File API for temporary processing and are automatically deleted once analysis is complete.",
    color: "#0d9488",
    bg: "#f0fdfa",
    border: "#ccfbf1",
    badge: "Data Minimisation",
  },
  {
    icon: Clock,
    title: "Temporary Processing Only",
    description:
      "All file processing occurs within a temporary, ephemeral environment. The Google Gemini API holds files for the minimum time required to complete analysis. No copies are made. Processing logs do not retain the video content.",
    color: "#3b82f6",
    bg: "#eff6ff",
    border: "#dbeafe",
    badge: "Ephemeral Data",
  },
  {
    icon: UserCheck,
    title: "Human Review Required",
    description:
      "No AI-generated risk assessment produces an outcome without mandatory human administrator review. Human experts retain full authority to approve, override, or reject any AI finding. Automation is advisory, never deterministic.",
    color: "#7c3aed",
    bg: "#f5f3ff",
    border: "#ede9fe",
    badge: "Human-In-The-Loop",
  },
  {
    icon: CheckSquare,
    title: "Consent-Based Submission",
    description:
      "Every video submission requires explicit, informed user consent before processing begins. Users are clearly informed of what analysis will occur, who will review the results, and what actions may follow. Consent can be withdrawn prior to submission.",
    color: "#16a34a",
    bg: "#f0fdf4",
    border: "#bbf7d0",
    badge: "Informed Consent",
  },
  {
    icon: Globe,
    title: "GDPR-Inspired Principles",
    description:
      "SafeGuard MU is designed in accordance with GDPR-inspired principles including purpose limitation, data minimisation, storage limitation, and transparency. While Mauritius applies its own data protection framework, we exceed its minimum requirements.",
    color: "#d97706",
    bg: "#fffbeb",
    border: "#fde68a",
    badge: "Privacy by Design",
  },
  {
    icon: Brain,
    title: "Responsible AI Framework",
    description:
      "SafeGuard MU uses Google Gemini 2.5 Pro in accordance with Google's Responsible AI principles. The system is designed to support, not replace, human judgment. AI outputs are explicitly labelled as assistive, non-diagnostic, and subject to human override.",
    color: "#dc2626",
    bg: "#fef2f2",
    border: "#fecaca",
    badge: "Responsible AI",
  },
];

const faqItems = [
  {
    question: "Does SafeGuard MU store my video permanently?",
    answer:
      "No. Videos are never stored on SafeGuard MU servers. They are passed directly to the Google Gemini File API for temporary processing. Once analysis completes, the file is immediately deleted by the API. No video content is retained.",
  },
  {
    question: "Can SafeGuard MU diagnose medical conditions?",
    answer:
      "No. SafeGuard MU is not a medical device and does not provide medical diagnoses. The platform generates AI-assisted risk assessments based on observable behaviours. All reports are reviewed by human administrators and are advisory only. No clinical conclusions are made.",
  },
  {
    question: "Who has access to the generated reports?",
    answer:
      "AI-generated reports are accessible only to authorised SafeGuard MU administrators who are responsible for the human review process. Report access is scoped, logged, and audited. Submitters receive only the outcome notification, not the full admin-facing report.",
  },
  {
    question: "What personal data does SafeGuard MU collect?",
    answer:
      "SafeGuard MU is designed around data minimisation. No account creation is required for submission. The platform may collect an optional submission description and consent timestamp. No biometric identifiers are extracted or stored. Video frames are not saved.",
  },
  {
    question: "How is the AI risk score calculated?",
    answer:
      "The risk score (0–100) is generated by Google Gemini 2.5 Pro based on multimodal analysis of the video content. It is a normalised composite of multiple dimensions including behavioural indicators, environmental factors, and emotional tone. The score is advisory and subject to human review and override.",
  },
  {
    question: "What happens if a human administrator disagrees with the AI?",
    answer:
      "Human administrators have full authority to override the AI-determined risk level, add contextual notes, approve or flag any report, and determine the final outcome. The AI assessment is always treated as a starting point for human expert review — never a final determination.",
  },
  {
    question: "Is submission consent mandatory?",
    answer:
      "Yes. Every submission requires explicit, informed consent before any processing occurs. Users must acknowledge the processing purpose, the use of Google Gemini AI, the human review step, and the non-diagnostic nature of the platform. Submission without consent is not possible.",
  },
  {
    question: "How does SafeGuard MU comply with Mauritius data protection law?",
    answer:
      "SafeGuard MU is built in alignment with Mauritius's Data Protection Act 2017 (DPA) and draws on GDPR principles. Key controls include: purpose limitation (analysis only), data minimisation (no unnecessary collection), storage limitation (no permanent video retention), transparency (clear privacy notices), and consent (explicit prior consent).",
  },
];

export default function PrivacyPage() {
  return (
    <div className="flex flex-col min-h-screen">
      <Navbar />

      <main className="flex-1">
        {/* Hero */}
        <div className="sg-hero-gradient text-white py-16">
          <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 text-center">
            <div className="inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-white/10 border border-white/20 mb-5 mx-auto">
              <Lock className="w-8 h-8 text-white" />
            </div>
            <h1 className="text-3xl sm:text-4xl font-bold mb-4">
              Privacy &amp; Ethics
            </h1>
            <p className="text-slate-300 text-lg max-w-2xl mx-auto leading-relaxed">
              SafeGuard MU is built on a foundation of trust, transparency, and
              responsible AI. Here is exactly how we protect your data and uphold
              ethical standards.
            </p>
          </div>
        </div>

        {/* Disclaimer banner */}
        <div id="disclaimer" className="bg-amber-50 border-b border-amber-200">
          <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-4">
            <div className="flex items-start gap-3">
              <AlertTriangle className="w-5 h-5 text-amber-600 shrink-0 mt-0.5" />
              <div className="text-sm text-amber-800">
                <strong>Important Medical Disclaimer:</strong> SafeGuard MU does
                not provide medical diagnoses, clinical assessments, or legal
                determinations. All AI-generated outputs are advisory and require
                mandatory human expert review before any action is taken. The
                platform is not a substitute for professional medical, psychological,
                or legal counsel.
              </div>
            </div>
          </div>
        </div>

        {/* Privacy Principles */}
        <section className="sg-section-pad bg-white">
          <div className="sg-container">
            <div className="text-center mb-12">
              <div className="inline-flex items-center gap-2 bg-[#f0fdfa] text-[#0d9488] rounded-full px-4 py-1.5 text-sm font-semibold mb-4">
                <Shield className="w-4 h-4" />
                Our Privacy Principles
              </div>
              <h2 className="text-3xl font-bold text-[#0f172a] mb-4">
                Six Core Privacy &amp; Ethics Commitments
              </h2>
              <p className="text-slate-500 max-w-xl mx-auto">
                Every aspect of SafeGuard MU has been designed with these
                commitments at its core — not as afterthoughts.
              </p>
            </div>

            <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-5">
              {privacyPrinciples.map((principle) => {
                const Icon = principle.icon;
                return (
                  <div
                    key={principle.title}
                    className="group p-6 rounded-2xl border-2 sg-card-hover transition-all duration-200"
                    style={{
                      borderColor: principle.border,
                      backgroundColor: principle.bg,
                    }}
                  >
                    <div className="flex items-start gap-4 mb-4">
                      <div
                        className="w-11 h-11 rounded-xl flex items-center justify-center shrink-0 shadow-sm"
                        style={{ backgroundColor: principle.color }}
                      >
                        <Icon className="w-5 h-5 text-white" />
                      </div>
                      <span
                        className="text-xs font-bold uppercase tracking-wider px-2.5 py-1 rounded-full mt-1"
                        style={{
                          backgroundColor: `${principle.color}15`,
                          color: principle.color,
                        }}
                      >
                        {principle.badge}
                      </span>
                    </div>
                    <h3 className="font-bold text-[#0f172a] mb-2 text-base">
                      {principle.title}
                    </h3>
                    <p className="text-slate-600 text-sm leading-relaxed">
                      {principle.description}
                    </p>
                  </div>
                );
              })}
            </div>
          </div>
        </section>

        {/* Data flow diagram */}
        <section id="ethics" className="sg-section-pad bg-[#f8fafc]">
          <div className="sg-container">
            <div className="text-center mb-10">
              <h2 className="text-3xl font-bold text-[#0f172a] mb-3">
                What Happens to Your Data
              </h2>
              <p className="text-slate-500 max-w-lg mx-auto">
                A transparent, step-by-step view of the data lifecycle within
                SafeGuard MU.
              </p>
            </div>

            <div className="max-w-2xl mx-auto">
              {[
                {
                  step: "1",
                  action: "User uploads video",
                  detail: "Consent verified → HTTPS encrypted transfer",
                  icon: Eye,
                  state: "In Transit",
                  stateColor: "bg-blue-100 text-blue-700",
                },
                {
                  step: "2",
                  action: "Video reaches Gemini File API",
                  detail: "Temporary file held in Google's secure environment",
                  icon: Database,
                  state: "Temporary",
                  stateColor: "bg-purple-100 text-purple-700",
                },
                {
                  step: "3",
                  action: "Gemini 2.5 Pro analyses content",
                  detail: "No video frames stored — analysis only",
                  icon: Brain,
                  state: "Processing",
                  stateColor: "bg-teal-100 text-teal-700",
                },
                {
                  step: "4",
                  action: "Structured JSON report returned",
                  detail: "Video file deleted from API immediately",
                  icon: FileText,
                  state: "Report Only",
                  stateColor: "bg-green-100 text-green-700",
                },
                {
                  step: "5",
                  action: "Human administrator reviews",
                  detail: "Report (not video) reviewed by expert admin",
                  icon: UserCheck,
                  state: "Text Only",
                  stateColor: "bg-amber-100 text-amber-700",
                },
                {
                  step: "6",
                  action: "Report finalised & data cleared",
                  detail: "Outcome documented, all processing data purged",
                  icon: Shield,
                  state: "Data Cleared",
                  stateColor: "bg-red-100 text-red-700",
                },
              ].map((item, i) => {
                const Icon = item.icon;
                const isLast = i === 5;
                return (
                  <div key={item.step} className="flex gap-4">
                    <div className="flex flex-col items-center">
                      <div className="w-10 h-10 rounded-xl bg-[#0f172a] flex items-center justify-center shrink-0 shadow-md">
                        <Icon className="w-4.5 h-4.5 text-[#2dd4bf]" />
                      </div>
                      {!isLast && (
                        <div className="flex-1 w-0.5 bg-slate-200 my-2 min-h-6" />
                      )}
                    </div>
                    <div className={`pb-5 flex-1 ${isLast ? "" : ""}`}>
                      <div className="bg-white rounded-xl border border-slate-100 p-4 shadow-sm">
                        <div className="flex items-center justify-between gap-2 mb-1">
                          <span className="font-bold text-[#0f172a] text-sm">
                            {item.action}
                          </span>
                          <span
                            className={`text-xs font-semibold px-2 py-0.5 rounded-full shrink-0 ${item.stateColor}`}
                          >
                            {item.state}
                          </span>
                        </div>
                        <p className="text-xs text-slate-500">{item.detail}</p>
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        </section>

        {/* FAQ */}
        <section id="consent" className="sg-section-pad bg-white">
          <div className="sg-container max-w-3xl">
            <div className="text-center mb-10">
              <h2 className="text-3xl font-bold text-[#0f172a] mb-3">
                Frequently Asked Questions
              </h2>
              <p className="text-slate-500">
                Clear answers to common questions about privacy, data handling, and
                AI use within SafeGuard MU.
              </p>
            </div>

            <Accordion className="space-y-2">
              {faqItems.map((item, i) => (
                <AccordionItem
                  key={i}
                  value={`item-${i}`}
                  className="border border-slate-200 rounded-xl overflow-hidden px-4 data-[state=open]:border-[#0d9488] data-[state=open]:bg-[#f0fdfa] transition-colors"
                >
                  <AccordionTrigger className="text-sm font-semibold text-[#0f172a] py-4 hover:no-underline hover:text-[#0d9488] text-left">
                    {item.question}
                  </AccordionTrigger>
                  <AccordionContent className="text-sm text-slate-600 leading-relaxed pb-4">
                    {item.answer}
                  </AccordionContent>
                </AccordionItem>
              ))}
            </Accordion>
          </div>
        </section>

        {/* Responsible AI disclaimer */}
        <section className="sg-section-pad bg-[#0f172a]">
          <div className="sg-container max-w-3xl text-center">
            <div className="w-14 h-14 rounded-2xl bg-[#0d9488]/20 border border-[#0d9488]/30 flex items-center justify-center mx-auto mb-5">
              <Brain className="w-7 h-7 text-[#2dd4bf]" />
            </div>
            <h2 className="text-2xl sm:text-3xl font-bold text-white mb-4">
              Responsible AI Commitment
            </h2>
            <p className="text-slate-400 leading-relaxed mb-6">
              SafeGuard MU is powered by Google Gemini 2.5 Pro and is deployed in
              strict accordance with Google&apos;s AI Principles. The platform
              treats all AI outputs as provisional, advisory, and subject to
              mandatory human review. SafeGuard MU will never automate any outcome
              without human expert validation. The platform will never be used for
              surveillance, profiling, or punitive action without due process.
            </p>
            <div className="grid sm:grid-cols-3 gap-4 text-sm">
              {[
                { title: "Advisory Only", desc: "AI outputs inform, never decide" },
                { title: "Human Authority", desc: "Experts override AI at all times" },
                { title: "Transparent", desc: "All AI logic is explainable" },
              ].map((item) => (
                <div
                  key={item.title}
                  className="bg-white/5 border border-white/10 rounded-xl p-4"
                >
                  <div className="font-bold text-white mb-1">{item.title}</div>
                  <div className="text-slate-400 text-xs">{item.desc}</div>
                </div>
              ))}
            </div>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  );
}
